---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
spec:
  containers:
    - name: nginx
      image: nginx:stable-alpine3.17-slim
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
