---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  namespace: default
spec:
  automountServiceAccountToken: false
  containers:
    - image: ubuntu
      command:
        - sleep
        - "3600"
      imagePullPolicy: IfNotPresent
      name: ubuntu
  restartPolicy: Always
