---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-explorer-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: api-explorer-role
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
      - services
      - configmaps
      - secrets
      - serviceaccounts
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - clusterroles
      - clusterrolebindings
      - roles
      - rolebindings
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "apps"
    resources:
      - deployments
      - daemonsets
      - statefulsets
      - replicasets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "authorization.k8s.io"
    resources:
      - selfsubjectaccessreviews
      - selfsubjectrulesreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: api-explorer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: api-explorer-role
subjects:
  - kind: ServiceAccount
    name: api-explorer-sa
    namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: api-explorer
  namespace: default
  labels:
    app: api-explorer
spec:
  serviceAccountName: api-explorer-sa
  containers:
    - name: attacker
      image: alpine:3.19
      command:
        - sleep
        - "3600"
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
