apiVersion: v1
kind: Pod
metadata:
  name: kube-proxy-workshop-cluster-worker
  namespace: kube-system
  labels:
    component: kube-proxy
spec:
  containers:
    - image: busybox
      command:
        - sleep
        - "3600"
      imagePullPolicy: IfNotPresent
      name: kube-proxy
  restartPolicy: Always
