apiVersion: v1
kind: Service
metadata:
  name: nft-store
  labels:
    app: nft-store
  namespace: lab-1
spec:
  type: NodePort
  ports:
    - port: 8080
      name: http
  selector:
    app: nft-store