---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: custom-ca-secret
  namespace: cert-manager
data:
  tls.crt: <base64 encoded public key>
  tls.key: <base64 encoded private key>
