apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-hunter
  namespace: default
secrets:
  - name: kube-hunter-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: kube-hunter-secret
  annotations:
    kubernetes.io/service-account.name: kube-hunter
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-hunter-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-hunter-role-binding
roleRef:
  kind: ClusterRole
  name: kube-hunter-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: kube-hunter
    namespace: default
