---
apiVersion: v1
kind: Service
metadata:
  name: echo-server-nodeport
  namespace: echo-server
spec:
  type: NodePort
  selector:
    app: echo-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30082
