---
apiVersion: v1
kind: Service
metadata:
  name: dvwa-nodeport
  namespace: dvwa
spec:
  type: NodePort
  selector:
    app: dvwa
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081
