apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lab-1

resources:
  - ../../base

patches:
  - path: service.yaml
    target:
      kind: Service
  - path: secret.yaml
    target:
      kind: Secret
  - path: deployment.yaml
    target:
      kind: Deployment
